In [ ]:
import torch


In [ ]:
#defining a Empty Matrix(tensor) 
x = torch.empty(size=(5,5))
x

tensor([[7.6720e-36, 0.0000e+00, 7.0065e-44, 6.7262e-44, 6.3058e-44],
        [6.7262e-44, 7.4269e-44, 6.3058e-44, 7.1466e-44, 6.7262e-44],
        [1.1771e-43, 6.7262e-44, 7.5670e-44, 8.1275e-44, 7.4269e-44],
        [7.7071e-44, 8.1275e-44, 7.0065e-44, 7.2868e-44, 6.4460e-44],
        [6.8664e-44, 7.4269e-44, 7.9874e-44, 7.0065e-44, 7.1466e-44]])

In [ ]:
#defining a Empty Matrix(tensor) 
x_r = torch.rand(size=(2,2))
x_r


tensor([[0.3772, 0.5888],
        [0.2176, 0.4007]])

In [ ]:
#defining a Matrix(tensor) of zeroes
x_0 = torch.zeros(size=(1,1), dtype=torch.int)
print(x_0)
#defining a Matrix(tensor) of ones
x_1 = torch.ones(size=(1,1))
print(x_1)

tensor([[0]], dtype=torch.int32)
tensor([[1.]])


In [ ]:
#tensor with predifined values

x_d = torch.tensor([[5,5,5,],[6,6,6],[8,8,8]], dtype=torch.long)
x_d

tensor([[5, 5, 5],
        [6, 6, 6],
        [8, 8, 8]])

In [ ]:
x_u = torch.rand_like(x_d,dtype=torch.float)
x_u

tensor([[0.8537, 0.1085, 0.8492],
        [0.6608, 0.3676, 0.2480],
        [0.0407, 0.4817, 0.2768]])

In [ ]:
x_u.size()

torch.Size([3, 3])

In [ ]:
#Operation
x = torch.ones(3,3, dtype=torch.float)
y = torch.tensor([[2,2,2],[1,1,1],[3,3,3]], dtype=torch.float32)
print("x-> ", x)
print("y-> ", y)


x->  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
y->  tensor([[2., 2., 2.],
        [1., 1., 1.],
        [3., 3., 3.]])


In [ ]:
print(x+y)

tensor([[3., 3., 3.],
        [2., 2., 2.],
        [4., 4., 4.]])


In [ ]:
z = torch.add(x,y)

In [ ]:
print(z)

tensor([[3., 3., 3.],
        [2., 2., 2.],
        [4., 4., 4.]])


In [ ]:
result = torch.zeros(3,3)
torch.matmul(x,y, out=result)
print(result)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [ ]:
a = torch.ones(2,2, dtype=torch.float)
b = torch.tensor([[2,2,],[1,1]], dtype=torch.float32)
print("a-> ", a)
print("b-> ", b)

a->  tensor([[1., 1.],
        [1., 1.]])
b->  tensor([[2., 2.],
        [1., 1.]])


In [ ]:
c = torch.zeros(2,2)
torch.matmul(a,b, out=c)
print(c)

tensor([[3., 3.],
        [3., 3.]])


In [ ]:
print("y-> ",y)
print("y_transporse-> ", y.t_())

y->  tensor([[2., 2., 2.],
        [1., 1., 1.],
        [3., 3., 3.]])
y_transporse->  tensor([[2., 1., 3.],
        [2., 1., 3.],
        [2., 1., 3.]])


In [ ]:
y

tensor([[2., 1., 3.],
        [2., 1., 3.],
        [2., 1., 3.]])

In [ ]:
y[:,1]

tensor([1., 1., 1.])

In [ ]:
a1 = torch.randn(1)
print(a1)
print(a1.item())

tensor([-0.1496])
-0.14955879747867584


In [ ]:
g =torch.ones(2,2, requires_grad=True)

In [ ]:
g

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
g.requires_grad

True

In [ ]:
gy = (g*2).mean()

In [ ]:
print(gy)

tensor(2., grad_fn=<MeanBackward0>)


In [ ]:
gy.backward()

In [ ]:
gy.grad

/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [ ]:
g.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [ ]:
gy

tensor(2., grad_fn=<MeanBackward0>)